### PR TITLE
condchan: simplify ChanPool

### PR DESCRIPTION
**Pull request by bcmills**
I do not guarantee that this is free from bugs, but the general idea should be sound.

### CODE REVIEW

**Comment by bcmills** [comment]
I should note that this implementation slightly weakens the “`Close` should interrupt `Get`” property: it does reliably interrupt `Get` eventually, but pending `Get` calls will block until the number of *active* connections drops below the limit.

That could be fixed (at a small cost in LoC) by changing the `closed` field from a boolean to a channel.

**Comment by cespare** [comment]
> That could be fixed (at a small cost in LoC) by changing the `closed` field from a boolean to a channel.

Can you describe that in a bit more detail? I don't see how it would work, since you can't select on a channel and a semaphore acquisition at the same time. (Or do you also mean spawning an extra goroutine per `Get`?)

**Comment by cespare** [comment]
Thanks for this, btw!

**Comment by bcmills** [comment]
> I don't see how it would work, since you can't select on a channel and a semaphore acquisition at the same time.

Hmm, good point. Will think a bit and get back to you.

The cheating way to do it would be to store a `context.Context` in the `Pool` struct and use that instead of `context.TODO()`: then you can just cancel it in `Close`, but you can't use a real `Context`.

**Comment by bcmills** [comment]
The slightly-less-cheaty way to do it would be to add a `Close` method to `*semaphore.Weighted` that would terminate pending calls to `Acquire` (and cause future calls to `Acquire` and `TryAcquire` to fail).

**Comment by cespare** [comment]
Maybe we need `semaphore.AcquireChan` ;)

**Comment by bcmills** [comment]
I was wrong; it's actually shorter with `closed` as a channel. :)

**Comment by bcmills** [comment]
> Maybe we need `semaphore.AcquireChan` ;)

That would be pretty dangerous: if the caller abandons the `Acquire` they need to give up their slot in the queue. (If we returned a channel they could wait on, we would also have to return an “abandon” callback, and it would be really easy to accidentally omit or duplicate the `abandon()` call.)

**Comment by cespare** [comment]
Hey, I like this one a lot more. Nice.

**Comment by cespare** [comment]
Point made. We have some internal connection pools which use a pattern like this these days :)

**Pull request closed without merging**
