### PR TITLE
Add ServeFSFile/ServeFSContent proposal

### PR DESCRIPTION
**Pull request by cespare**
Rendered text: https://github.com/cespare/misc/blob/httpfsproposal/httpfsproposal/proposal.md

### CODE REVIEW

**Comment by cespare** [comment]
@dmac @josharian @mvdan @dominikh -- I'm planning on sending a Go proposal but I'm interested in gathering a little feedback from others first so I can polish the proposal before publishing. If any of you have time to read this over and have any opinions, that would be very helpful! And no worries if not. Thanks.

**Comment by dominikh** [comment]
I don't really know enough about net/http or io/fs to have an opinion. I didn't spot any obvious issues with the proposal.

**Comment by josharian** [comment]
I'm in a similar position to @dominikh.

**Comment by mvdan** [comment]
Also not being an expert on net/http, it sounds fine. I'm not a big fan of the signature you chose for `ServeFSContent` but I agree that there isn't a clearly better option. The `fs.File` option is cleaner at first glance, and I don't see it being passed separately from `fs.FS` as a problem. But I do agree that `Close` not being used is misleading, plus note how `os.dirFS.Stat` calls the real `os.Stat` every time - we likely want the API to encourage one `os.Stat` call upfront, as opposed to one call per request being handled.

**Comment by cespare** [comment]
Thanks guys. I sent https://github.com/golang/go/issues/51971.

**Comment by dmac** [comment]
Late to the party, but this seems like a good proposal. I like the generality of `ServeReader`, and it's tempting to only propose the addition of that one new function, since it's just more general enough than `ServeContent` that it can handle an `fs.FS` (but isn't limited to it). The convenience of `ServeFSFile` might be nice to have, though.

**Pull request closed without merging**
